########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = ["${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml"]

# Repository Name
name = "omniverse-lidar-live-synthetic-data"

[repo_build.licensing]
enabled = false

[repo_build.msbuild]
vs_version = "vs2019"

[repo_docs]
name = "MF Lidar live synthetic data"
project = "omniverse-lidar-live-synthetic-data"
sphinx_exclude_patterns = [
    "_build",
    "tools",
    "VERSION.md",
    "source/extensions/*/docs/Overview.md",
    "source/extensions/*/docs/CHANGELOG.md",
]

[repo_docs.kit]
extensions = [
    "mf.ov.lidar_live_synth"
]

[repo_package.packages."platform:windows-x86_64".docs]
windows_max_path_length = 0
