########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = ["${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml"]

# Repository Name
name = "kit-extension-template-cpp"

[repo_build.licensing]
enabled = false

[repo_build.msbuild]
vs_version = "vs2019"

[repo_docs]
name = "Kit Extension Template C++"
project = "kit-extension-template-cpp"
sphinx_exclude_patterns = [
    "_build",
    "tools",
    "VERSION.md",
    "source/extensions/*/docs/Overview.md",
    "source/extensions/*/docs/CHANGELOG.md",
]

[repo_docs.kit]
extensions = [
    "omni.example.cpp.actions",
    "omni.example.cpp.commands",
    "omni.example.cpp.hello_world",
    "omni.example.cpp.omnigraph_node",
    "omni.example.cpp.pybind",
    "omni.example.cpp.ui_widget",
    "omni.example.cpp.usd",
    "omni.example.cpp.usd_physics",
    "omni.example.python.hello_world",
    "omni.example.python.ui",
]

[repo_package.packages."platform:windows-x86_64".docs]
windows_max_path_length = 0
