[package]
version = "0.1.1"

title = "MF Lidar live synthetic data"
description = "Send real-time Lidar synthetic point cloud data from Omniverse to third party software."
authors = ["Moment Factory","Frederic Lestage","Steven Beliveau"]

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
repository = "https://github.com/MomentFactory/Omniverse-Lidar-extension"

category = "Graph"
keywords = ["lidar", "UDP", "omnigraph", "Graph", "Node", "OmniGraph", "synthetic", "realtime"]

preview_image = "data/preview.png"
icon = "data/icon.png"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[dependencies]
"omni.graph" = {}

[[python.module]]
name = "mf.ov.lidar_live_synth"

[documentation]
pages = [
    "docs/README.md",
    "docs/CHANGELOG.md",
]
